### ISSUE TITLE
Just wanted to say this is awesome...I was writing the same thing

### ISSUE THREAD

**Issue by shanselman** [gabe565/streamdeck-nightscout#24]
Just wanted to say this is awesome...I was writing the same thing

**Comment by shanselman** [comment]
usually when doing this you'd "npm run build" per https://www.npmjs.com/package/@elgato/streamdeck - how are you building and testing this?

**Comment by gabe565** [comment]
Agh sorry, I've been really neglecting this repo. So, I still have to do that, but there is a [GitHub Action workflow](https://github.com/gabe565/streamdeck-nightscout/blob/main/.github/workflows/build.yaml) to do the build and test. Then, I use [AdamCarballo/streamdeck-distribution-tool](https://github.com/AdamCarballo/streamdeck-distribution-tool) to build the package!
